<?php
// $Id$
/**
 * @file
 * Inkind donations for Donor Rally.
 */
include_once('dr_inkind.features.inc');

/**
 * Implementation of hook_form_alter().
 */
function dr_inkind_form_dr_base_settings_form_alter(&$form, $form_state) {
  $form['point_scales']['food'] = array(
    '#title' => t('Food scale'),
    '#description' => t('Scaling factor to turn pounds of food into points'),
    '#type' => 'textfield',
    '#default_value' => variable_get('dr_base_food_scale', 1.0),
    '#required' => TRUE,
  );
  $form['point_scales']['volunteer'] = array(
    '#title' => t('Volunteer scale'),
    '#description' => t('Scaling factor to turn volunteer shifts into points'),
    '#type' => 'textfield',
    '#default_value' => variable_get('dr_base_volunteer_scale', 1.0),
    '#required' => TRUE,
  );
}

/**
 * Implementation of hook_dr_base_team_stat_categories().
 */
function dr_inkind_dr_base_team_stat_categories() {
  return array(
    'food' => array(
      'label' => t('Food (lbs)'),
      'goal_field' => 'field_food_goal',
      'total_field' => 'field_food',
    ),
    'volunteer' => array(
      'label' => t('Volunteer shifts'),
      'goal_field' => 'field_volunteer_goal',
      'total_field' => 'field_volunteer',
    ),
  );
}

/**
 * Implementation of hook_dr_base_point_scales().
 */
function dr_inkind_dr_base_point_scales() {
  return array(
    'food' => variable_get('dr_base_food_scale', 1.0),
    'volunteer' => variable_get('dr_base_volunteer_scale', 1.0),
  );
}
