<?php

// $Id$

/**
 * @file
 * Donor Rally module. Allows teams/groups to "compete" in fundraising campaigns.
 * See README.txt for more information.
 */

/**
 * Team content type.
 */
define('DONOR_RALLY_CONTENT_PROFILE_TYPE', 'team');

/**
 * Implements hook_menu().
 */
function dr_base_menu() {
  $items = array();
  $items['admin/settings/dr-base'] = array(
    'title' => 'Donor Rally',
    'description' => 'Global settings for Donor Rally',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dr_base_settings_form'),
    'access arguments' => array('administer donor rally'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'dr_base.admin.inc',
  );

  $items['admin/settings/dr-base/global'] = array(
    'title' => 'Global settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  return $items;
}

/**
 * Implements hook_perm().
 */
function dr_base_perm() {
  return array('administer donor rally');
}

/**
 * Implements hook_theme().
 */
function dr_base_theme($existing, $type, $theme, $path) {
  $base = array(
    'arguments' => array('vars' => array())
  );
  return array(
    'dr_base_team_progress_thermometer' => array(
      'template' => 'dr-base-team-progress-thermometer',
    ) + $base,
    'dr_base_team_progress_stats' => array(
      'template' => 'dr-base-team-progress-stats',
    ) + $base,
    'dr_base_team_leaderboard_button' => $base,
    'dr_base_team_page_button' => $base,
    'dr_base_new_blog_post_button' => $base,
    'dr_base_team_coordinator_login_button' => $base,
    'dr_base_team_coordinator_account_button' => $base,
  );
}

/**
 * Implements hook_profile_alter().
 */
function dr_base_profile_alter(&$account) {
  if ($node = content_profile_load(DONOR_RALLY_CONTENT_PROFILE_TYPE, $account->uid)) {
    $account->content['dr-base-team-info'] = array(
      '#type' => 'user_profile_category',
      '#title' => t('Team information'),
      '#attributes' => array('class' => 'dr-base-profile-team-info'),
    );
    $account->content['dr-base-team-info']['link'] = array(
      '#type' => 'user_profile_item',
      '#title' => t('Team Page link&mdash;give this to your team'),
      '#value' => '<span class="dr-base-raw-url">'.
        url('node/'. $node->nid, array('absolute' => TRUE)) .
        '</span>',
    );
    unset($account->content['summary']);
  }
}

/**
 * Implements hook_cron().
 */
function dr_base_cron() {
  dr_base_refresh_all();
}

/**
 * Refreshes all teams' points and statistics by querying the payment
 * gateway and recalculating totals.
 */
function dr_base_refresh_all() {
  $cash_scale = (float)variable_get('dr_base_cash_scale', 1.0);
  $food_scale = (float)variable_get('dr_base_food_scale', 1.0);
  $volunteer_scale = (float)variable_get('dr_base_volunteer_scale', 1.0);

  $current_all = _dr_base_fetch_current_team_stats();
  foreach ($current_all as $nid => $now) {
    if ($cash = module_invoke(variable_get('dr_base_payment_gateway', 'dr_base_salsa'), 'dr_base_online_cash', $nid)) {
      $now['cash'] = $cash;
    }
    else {
      // no-op; we didn't get an online cash value from the payment
      // gateway for this team, so just use the current value for
      // calculating new totals
      $now['cash'] = 0;
    }
    // @TODO, abstract this out to exclude food and volunteer hours
    // unless the in-kind module/feature is enabled.
    db_query(
      'UPDATE {' . _dr_base_get_team_table() . '} SET ' .
        'field_cash_value = %f, ' .
        'field_total_points_value = (%f+%f)*%f + (%f+%f)*%f + (%f+%f)*%f, ' .
        'field_points_per_capita_value = ((%f+%f)*%f + (%f+%f)*%f + (%f+%f)*%f) / %d ' .
      'WHERE nid = %d',
      array(
        $now['cash'],
        $now['cash'], $now['field_offline_cash_value'], $cash_scale, $now['food'], $now['offline_food'], $food_scale, $now['volunteer'], $now['offline_volunteer'], $volunteer_scale,
        $now['cash'], $now['field_offline_cash_value'], $cash_scale, $now['food'], $now['offline_food'], $food_scale, $now['volunteer'], $now['offline_volunteer'], $volunteer_scale,
        $now['field_size_value'],
        $nid
      )
    );
  }
  drupal_flush_all_caches();
}

/**
 * Fetches current size, cash values, food values, volunteer values for all
 * teams (from the database).
 */
function _dr_base_fetch_current_team_stats() {
  $result = db_query('SELECT * FROM {' . _dr_base_get_team_table() . '}');

  $team_stats = array();
  while ($current = db_fetch_array($result)) {
    $nid = $current['nid'];
    $team_stats[$nid] = $current;
    unset($team_stats[$nid]['nid']);
    foreach ($team_stats[$nid] as $field => $value) {
      if (empty($value)) {
        $team_stats[$nid][$field] = 0.0;
      }
    }
  }

  return $team_stats;
}

/**
 * Get table where team information is stored.
 */
function _dr_base_get_team_table() {
  $field_cash = content_fields('field_cash');
  $database_info = content_database_info($field_cash);
  return $database_info['table'];
}

/**
 * Set up Salsa Tracking_Code aliases for debugging.
 */
function _dr_base_set_debug_aliases() {
  $team_stats = _dr_base_query_cash_aggregate();
  $team_names = array_keys($team_stats);

  // Find all team node ids and assign nids to each entry in $team_names.
  $team_aliases = array();
  $result = db_query("SELECT nid, title FROM {node} WHERE type = 'team'");
  $i = 0;
  while ($node = db_fetch_object($result)) {
    if (!isset($team_names[$i])) {
      break;
    }
    $team_aliases['by-nid'][$node->nid] = $team_names[$i];
    $team_aliases['by-name'][$team_names[$i]] = $node->nid;
    $i++;
  }
  drupal_set_message("Aliased $i out of " . count($team_names) . " teams...<br />" . dpr($team_aliases, true));
  variable_set('dr_base_debug_aliases', $team_aliases);
}

/**
 * Formats a value (points or raw) for display.
 */
function _dr_base_format_value($value) {
  return number_format($value, 0, '.', ',');
}

/**
 * Implementation of hook_donor_rally_team_stat_categories().
 */
function dr_base_donor_rally_team_stat_categories() {
  return array(
    'cash' => array(
      'label' => t('Cash ($)'),
      'goal_field' => 'field_cash_goal',
      'total_field' => 'field_cash',
    ),
  );
}

/**
 * Implementation of hook_donor_rally_point_scales().
 */
function dr_base_donor_rally_point_scales() {
  return array(
    'cash' => variable_get('dr_base_cash_scale', 1.0),
  );
}

/**
 * Calculate a team's statistics directly from node values.
 */
function dr_base_team_stats($node) {
  $point_scales = module_invoke_all('donor_rally_point_scales');
  $categories = module_invoke_all('donor_rally_team_stat_categories');

  $stats['total_raw'] = 0.0;
  $stats['total_raw_goal'] = 0.0;

  foreach ($categories as $type => $info) {
    $label = $info['label'];

    // Raw values (USD, pounds, shifts, etc.); points (scaled raw).
    $stats[$type .'_raw'] = $node->{'field_'. $type}[0]['value'] + $node->{'field_offline_' .$type}[0]['value'];
    $stats[$type .'_raw_goal'] = $node->{'field_'. $type .'_goal'}[0]['value'];

    // Points values.
    $stats[$type] = $stats[$type .'_raw'] * $point_scales[$type];
    $stats[$type .'_goal'] = $stats[$type .'_raw_goal'] * $point_scales[$type];

    // Totals.
    $stats['total_raw'] += $stats[$type];
    $stats['total_raw_goal'] += $stats[$type .'_goal'];

    // Labels.
    $stats[$type . '_label'] = $label;
  }

  // Provide a formatted version as well.
  foreach ($stats as $k => $v) {
    if (strpos($k, '_label') === FALSE) {
      $stats[$k .'_view'] = _dr_base_format_value($v);
    }
  }

  $stats['per_capita'] = $stats['total'] / $node->field_size[0]['value']; 
  return $stats;
}

/**
 * Implements hook_init().
 */
function dr_base_init() {
  /* We need our css occasionally on pages without our blocks on 'em...so just include it always */
  drupal_add_css(drupal_get_path('module', 'dr_base') .'/dr-base.css', 'module');
}

/**
 * Implements hook_block().
 */
function dr_base_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
     return array(
       0 => array(
         'info' => t('Team Progress Thermometer'),
         'cache' => BLOCK_NO_CACHE,
       ),
       1 => array(
         'info' => t('Donate Button'),
         'cache' => BLOCK_CACHE_PER_PAGE,
       ),
       2 => array(
         'info' => t('Leaderboard Button'),
         'cache' => BLOCK_CACHE_GLOBAL,
       ),
       3 => array(
         'info' => t('Team Progress Statistics'),
         'cache' => BLOCK_NO_CACHE,
       ),
       4 => array(
         'info' => t('Team Page Button'),
         'cache' => BLOCK_CACHE_PER_PAGE,
       ),
       5 => array(
         'info' => t('New Team Blog Post'),
         'cache' => BLOCK_CACHE_PER_PAGE,
       ),
       6 => array(
         'info' => t('Team Coordinator Log in Button'),
         'cache' => BLOCK_CACHE_GLOBAL,
       ),
       7 => array(
         'info' => t('Team Coordinator Dashboard Button'),
         'cache' => BLOCK_NO_CACHE,
       ),
       'site_thermometer' => array(
         'info' => t('Site-wide total/goal thermometer'),
         'cache' => BLOCK_CACHE_GLOBAL,
       ),
       'team_links' => array(
         'info' => t('Donor Rally Team/Account links'),
         'cache' => BLOCK_CACHE_PER_USER,
       ),
     );
    case 'configure':
      return array();
    case 'view':
      if ($delta === 'site_thermometer') {
        return array(
          'subject' => '',
          'content' => _dr_base_block_site_thermometer(),
        );
      }
      elseif ($delta === 'team_links') {
        return array(
          'subject' => '',
          'content' => _dr_base_block_team_links(),
        );
      }

      if (!$node) {
        $node = menu_get_object();
        if ($node && $node->type != DONOR_RALLY_CONTENT_PROFILE_TYPE) {
          $node = NULL;
        }
      }

      $vars = array();
      if ($node) {
        $vars = dr_base_team_stats($node);
        $vars['node'] = $node;
      }

      if ($delta === 1 ) {
        // Allow payment gateway to set the button.
        $button = module_invoke(variable_get('dr_base_payment_gateway', 'dr_base_salsa'), 'donor_rally_donate_button', $vars);
        return array(
          'subject' => '',
          'content' => $button,
        );
      }
      
      $theme_functions = array(
        0 => 'dr_base_team_progress_thermometer',
        2 => 'dr_base_team_leaderboard_button',
        3 => 'dr_base_team_progress_stats',
        4 => 'dr_base_team_page_button',
        5 => 'dr_base_new_blog_post_button',
        6 => 'dr_base_team_coordinator_login_button',
        7 => 'dr_base_team_coordinator_account_button',
      );
      if (isset($theme_functions[$delta])) {
        return array('subject' => '', 'content' => theme($theme_functions[$delta], $vars));
      }
  }
  return array('subject' => '', 'content' => '');
}

/**
 * Implementation of hook_views_api().
 */
function dr_base_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'dr_base'),
  );
}

/**
 * Preprocess thermometer vars for theming
 */
function dr_base_preprocess_dr_base_team_progress_thermometer(&$variables) {
  $vars = $variables['vars'];
  unset($variables['vars']);
  if ($vars['total_raw_goal'] == 0.0) {
    return;
  }

  $total_height = 188; /* Fairly arbitrary */
  $top_margin = 0;
  $top_halfheight = $bottom_halfheight = 52 / 2;
  $font_halfheight = 9; /* half of "line-height" for the style goal/points style */

  $vars['complete'] = $vars['total_raw'] / $vars['total_raw_goal'];
  $vars['success'] = $vars['complete'] >= 1.0;

  $vars['filled_height'] = (int)($total_height * min(1.0, $vars['complete']) + 0.5);
  $vars['empty_height'] = $total_height - $vars['filled_height'];

  if (!$vars['success']) {
    $vars['empty_top_top'] = $top_margin;
    $vars['empty_middle_top'] = $top_margin + $top_halfheight;
    $vars['empty_bottom_top'] = $vars['empty_middle_top'] + $vars['empty_height'];
  }

  $vars['filled_top_top'] = $top_margin /* + $top_halfheight - $top_halfheight */ + $vars['empty_height'];
  $vars['filled_middle_top'] = $vars['filled_top_top'] + $top_halfheight;
  $vars['filled_bottom_top'] = $vars['filled_middle_top'] + $vars['filled_height'];

  $vars['goal_top'] = $top_margin + $top_halfheight - $font_halfheight;
  $vars['points_top'] = max($vars['goal_top'] + $font_halfheight*2, $vars['goal_top'] + $vars['empty_height']);
  $variables += $vars;
}

/**
 * Preprocess variables for statistics block theming
 */
function dr_base_preprocess_dr_base_team_progress_stats(&$variables) {
  $variables += $variables['vars'];
  unset($variables['vars']);
  $variables['categories'] = module_invoke_all('donor_rally_team_stat_categories');
  if (count($variables['categories']) > 1) {
    $variables['categories']['total']['label'] = t('Total points');
  }
}

/**
 * Helper that constructs button markup.
 */
function dr_base_theme_button($class, $text, $link, $attr = array()) {
  return l($text, $link, array('html' => TRUE, 'attributes' => array('class' => 'dr-base-button '.$class) + $attr));
}

/**
 * Theme the "leaderboard" button block
 */
function theme_dr_base_team_leaderboard_button($vars) {
  return dr_base_theme_button(
    'dr-base-leaderboard-button',
    t('Team Ranking'),
    'leaderboard'
  );
}

/**
 * Theme the "team page" button block
 */
function theme_dr_base_team_page_button($vars) {
  return dr_base_theme_button(
    'dr-base-team-page-button',
    t('Team Page'),
    'node/'. $vars['node']->nid
  );
}

/**
 * Theme the "new blog post" button block
 */
function theme_dr_base_new_blog_post_button($vars) {
  if (user_access('create team_blog_post content')) {
    return '<div class="dr-base-new-blog-post-button">'.
      l(t('Write a new blog post'), 'node/add/team-blog-post') .
      '</div>';
  }
  return '';
}

/**
 * Theme the "Team coordinator login" button block
 */
function theme_dr_base_team_coordinator_login_button($vars) {
  global $user;
  if ($user->uid != 0) {
    return;
  }

  return dr_base_theme_button(
    'dr-base-team-coordinator-login-button',
    t('Team Coordinator Login'),
    'user/login'
  );
}

/**
 * Theme the "Team coordinator account/dashboard" button block
 */
function theme_dr_base_team_coordinator_account_button($vars) {
  global $user;
  if (!isset($vars['node']) || $vars['node']->uid != $user->uid) {
    return;
  }

  return dr_base_theme_button(
    'dr-base-team-coordinator-account-button',
    t('Team Dashboard'),
    'user'
  );
}

/**
 * Sitewide total/goal thermometer.
 */
function _dr_base_block_site_thermometer() {
  $goal = variable_get('dr_base_goal', 314159265);
  $total = _dr_base_get_total_points();
  $vars['total_raw_goal'] = $goal;
  $vars['total_raw'] = $total;
  $vars['total_raw_goal_view'] = _dr_base_format_value($goal);
  $vars['total_raw_view'] = _dr_base_format_value($total);

  $vars['edit_link'] = user_access('administer donor rally') ? l('Change campaign goal', 'admin/settings/dr-base', array('query' => drupal_get_destination())) : '';
  return theme('dr_base_team_progress_thermometer', $vars);
}

/**
 * Get total goal for all combined teams.
 *
 * @TODO This isn't actually used anymore, but it may be useful for
 * getting the total team goals at some point.
 */
function _dr_base_get_total_goal() {
  $goal = 0;
  $categories = module_invoke_all('donor_rally_team_stat_categories');
  foreach ($categories as $category => $info) {
    $field = content_fields($info['goal_field']);
    $db_info = content_database_info($field);
    $table = $db_info['table'];
    $column = $db_info['columns']['value']['column'];
    $goal += db_result(db_query("SELECT SUM(" . $column . ") FROM {" . $table . "}"));
  }
  return $goal;
}

/**
 * Get total points for all combined teams.
 */
function _dr_base_get_total_points() {
  $field = content_fields('field_total_points');
  $db_info = content_database_info($field);
  $table = $db_info['table'];
  $column = $db_info['columns']['value']['column'];
  return db_result(db_query("SELECT SUM(" . $column . ") FROM {" . $table . "}"));
}

/**
 * User account/team management links.
 */
function _dr_base_block_team_links() {
  if (!user_is_anonymous()) {
    global $user;
    $links = array(
      'edit-team' => array(
        'title' => t('Manage team'),
        'href' => "user/{$user->uid}/edit/team",
      ),
      'edit-account' => array(
        'title' => t('Manage account'),
        'href' => "user/{$user->uid}/edit",
      ),
      'logout' => array(
        'title' => t('Logout'),
        'href' => 'logout',
      ),
    );
  }
  else {
    $links = array(
      'login' => array(
        'title' => t('Manage team'),
        'href' => 'user/login',
      ),
      'create' => array(
        'title' => t('Create your team'),
        'href' => 'user/register',
      ),
    );
  }
  drupal_alter('dr_base_team_links', $links);
  return theme('links', $links);
}