<?php
// $Id$

/**
 * @file
 * Import/Export utilities for Donor Rally.
 */
include_once('dr_team_io.features.inc');

/**
 * Implementation of hook_menu().
 */
function dr_team_io_menu() {
  $items['admin/content/competitive-drive/import'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dr_team_io_import_form'),
    'access arguments' => array('administer donor rally'),
    'file' => 'dr_team_io.admin.inc',
  );

  return $items;
}
